language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - python setup.py install

script:
  - coverage run --source Aplos -m py.test
  
after_success:
 - coveralls